package cli

import (
	"assetx/src/core/imageProcessing"
	"fmt"
	"io"
)

func PrintRootHelp(writer io.Writer) {
	_, _ = fmt.Fprintln(writer, "assetx - generate and adapt game assets with multiple providers.")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Usage:")
	_, _ = fmt.Fprintln(writer, "  assetx [--config path/to/config.json] <command> [options]")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Commands:")
	_, _ = fmt.Fprintln(writer, "  image      Generate or edit an image asset")
	_, _ = fmt.Fprintln(writer, "  help       Show help for assetx or a command")
	_, _ = fmt.Fprintln(writer, "  version    Print version, target platform, commit, and commit date")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Currently implemented provider:")
	_, _ = fmt.Fprintln(writer, "  openai     Models: gpt-image-2, gpt-image-1.5")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Common help:")
	_, _ = fmt.Fprintln(writer, "  assetx help image")
	_, _ = fmt.Fprintln(writer, "  assetx help config")
	_, _ = fmt.Fprintln(writer, "  assetx image --help")
	_, _ = fmt.Fprintln(writer)
	PrintConfigSummary(writer)
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Example:")
	_, _ = fmt.Fprintln(writer, "  assetx image --model gpt-image-2 --background transparent --prompt \"create a battle win header\" --example example1.png --example-note \"screenshot of my game\" --example example2.png --example-note \"existing UI asset style reference\" --quality medium --size 1024x1024 --out assets/sprites/header.png")
}

func PrintImageHelp(writer io.Writer) {
	_, _ = fmt.Fprintln(writer, "assetx image - generate or edit an image asset.")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Usage:")
	_, _ = fmt.Fprintln(writer, "  assetx [--config path/to/config.json] image --prompt \"...\" --out path/to/output.png [options]")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Required:")
	_, _ = fmt.Fprintln(writer, "  --prompt string        Text prompt for the asset")
	_, _ = fmt.Fprintln(writer, "  --out path             Output path ending in .png, .jpg, .jpeg, or .webp")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Options:")
	_, _ = fmt.Fprintln(writer, "  --model string         gpt-image-2 or gpt-image-1.5 (default: gpt-image-2)")
	_, _ = fmt.Fprintln(writer, "  --avoid string         Thing to avoid in the image; repeat for multiple avoid items")
	_, _ = fmt.Fprintln(writer, "  --background string    auto, opaque, or transparent (default: auto)")
	_, _ = fmt.Fprintln(writer, "  --example path         Example/input image path; repeat for multiple examples")
	_, _ = fmt.Fprintln(writer, "  --example-note string  Required note for the matching --example; repeat once per --example")
	_, _ = fmt.Fprintln(writer, "  --quality string       auto, low, medium, or high (default: medium)")
	_, _ = fmt.Fprintln(writer, "  --size string          auto or WIDTHxHEIGHT (default: 1024x1024)")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Model and size rules:")
	_, _ = fmt.Fprintln(writer, "  gpt-image-2 accepts WIDTHxHEIGHT where both values are positive, divisible by 16, max 3840x2160, and aspect ratio is between 1:3 and 3:1.")
	_, _ = fmt.Fprintln(writer, "  gpt-image-1.5 accepts auto, 1024x1024, 1024x1536, or 1536x1024.")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Examples and references:")
	_, _ = fmt.Fprintln(writer, "  Repeat --example to pass multiple image references.")
	_, _ = fmt.Fprintln(writer, "  Every --example requires one matching --example-note in the same order.")
	_, _ = fmt.Fprintln(writer, "  assetx appends those notes to the prompt as a structured reference-notes section.")
	_, _ = fmt.Fprintln(writer, "  The current OpenAI provider sends examples to the image edit endpoint as repeated image[] parts.")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Avoid list:")
	_, _ = fmt.Fprintln(writer, "  Repeat --avoid for negative constraints. assetx appends them to the prompt as an Avoid section.")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Transparency:")
	_, _ = fmt.Fprintln(writer, "  gpt-image-1.5 can request transparent background directly.")
	_, _ = fmt.Fprintln(writer, "  gpt-image-2 does not support direct transparency; assetx requests a chroma background and post-processes matching chroma pixels into PNG alpha.")
	_, _ = fmt.Fprintln(writer, "  gpt-image-2 transparent output requires --out ending in .png.")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Examples:")
	_, _ = fmt.Fprintln(writer, "  assetx image --prompt \"16x16 slime sprite, idle frame\" --out assets/sprites/slime.png")
	_, _ = fmt.Fprintln(writer, "  assetx image --model gpt-image-2 --background transparent --prompt \"battle win header\" --avoid watermark --avoid \"text artifacts\" --quality medium --size 1024x1024 --out assets/ui/battle_win.png")
	_, _ = fmt.Fprintln(writer, "  assetx image --model gpt-image-1.5 --background transparent --prompt \"match this style\" --example refs/style.png --example-note \"existing asset style reference\" --example refs/screenshot.jpg --example-note \"screenshot of the target game scene\" --out assets/icons/gem.png")
}

func PrintConfigHelp(writer io.Writer) {
	_, _ = fmt.Fprintln(writer, "assetx config - configuration file format.")
	_, _ = fmt.Fprintln(writer)
	PrintConfigSummary(writer)
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "JSON example:")
	_, _ = fmt.Fprintln(writer, "{")
	_, _ = fmt.Fprintln(writer, "  \"proxy_base_url\": \"\",")
	_, _ = fmt.Fprintln(writer, "  \"api_key\": \"b64::base64_encoded_key_here\"")
	_, _ = fmt.Fprintln(writer, "}")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Proxy example:")
	_, _ = fmt.Fprintln(writer, "  \"proxy_base_url\": \"https://main.purroxy.org/openai/v1\"")
}

func PrintRemoveBackgroundHelp(writer io.Writer) {
	_, _ = fmt.Fprintln(writer, "assetx remove-bg - remove a solid color from an existing image and write a transparent PNG.")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Usage:")
	_, _ = fmt.Fprintln(writer, "  assetx remove-bg --in path/to/source.png --out path/to/output.png [options]")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Required:")
	_, _ = fmt.Fprintln(writer, "  --in path           Input image path")
	_, _ = fmt.Fprintln(writer, "  --out path          Output path ending in .png")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Options:")
	_, _ = fmt.Fprintf(writer, "  --color string      Hex color to remove, default %s\n", imageProcessing.ChromaHexColor)
	_, _ = fmt.Fprintf(writer, "  --tolerance int     Sum RGB distance tolerance, default %d\n", imageProcessing.ChromaDistanceTolerance)
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Examples:")
	_, _ = fmt.Fprintln(writer, "  assetx remove-bg --in tmp/chroma.png --out assets/icon.png")
	_, _ = fmt.Fprintln(writer, "  assetx remove-bg --in tmp/source.jpg --out assets/icon.png --color \"#ff00ff\" --tolerance 120")
}

func PrintVersionHelp(writer io.Writer) {
	_, _ = fmt.Fprintln(writer, "assetx version - print build identity.")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Usage:")
	_, _ = fmt.Fprintln(writer, "  assetx version")
	_, _ = fmt.Fprintln(writer, "  assetx --version")
	_, _ = fmt.Fprintln(writer)
	_, _ = fmt.Fprintln(writer, "Output includes the assetx version, GOOS/GOARCH, VCS commit, dirty marker, commit date, and Go compiler version when available.")
}

func PrintConfigSummary(writer io.Writer) {
	_, _ = fmt.Fprintln(writer, "Config:")
	_, _ = fmt.Fprintln(writer, "  Default path: ~/.assetx/config.json")
	_, _ = fmt.Fprintln(writer, "  Override path: assetx --config some/other/path/config.json <command>")
	_, _ = fmt.Fprintln(writer, "  proxy_base_url empty string uses the default API base for the current provider.")
	_, _ = fmt.Fprintln(writer, "  proxy_base_url non-empty must be an OpenAI-compatible API base URL for the current OpenAI provider.")
	_, _ = fmt.Fprintln(writer, "  api_key may be raw or prefixed with b64:: followed by a base64-encoded key.")
}
